title: Hacker blog
description: GitHub Pages for writeups, programming, Walkthroughts
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      type: "pages"
      layout: default
